name: nz_logger
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  logging: ^1.2.0

dev_dependencies:
  nz_lint: ^1.0.0
