name: nz_logger
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  logging: ^1.2.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
