// ignore_for_file: avoid_redundant_argument_values, constant_identifier_names

/// Flutter icons NotZero
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NotZero
///      fonts:
///       - asset: fonts/NotZero.ttf
///
///
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
library;

import 'package:flutter/widgets.dart';

class NotZeroIcons {
  NotZeroIcons._();

  static const _kFontFam = 'NotZero';
  static const String? _kFontPkg = null;

  static const IconData zero = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData github_circled = IconData(
    0xf09b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData telegram_plane = IconData(
    0xf3fe,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
