include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - 'lib/**/*.g.dart'
    - 'lib/get_it.config.dart'

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    unused_element: false
    sort_pub_dependencies: false
