targets:
  $default:
    builders:
      drift_dev:
        options:
          # This is necessary for saving microseconds accuracy
          store_date_time_values_as_text: true
          generate_connect_constructor: true
