name: not_zero

scripts:
  generate:
    exec: dart run build_runner build -d
    orderDependents: true
    packageFilters:
      dependsOn:
        - build_runner
  l10n:
    exec: dart run slang
    packageFilters:
      dependsOn:
        - slang
  fix:
    exec: dart fix --apply .

packages:
  - .
  - packages/**
  - packages/features/**
