name: not_zero_storage
description: |
  Submodule of "Not Zero" app, providing it with a ways of storing persistent
  data.
version: 0.0.1
publish_to: none

environment:
  sdk: '>=2.17.6 <3.0.0'
  flutter: '>=1.17.0'

dependencies:
  flutter:
    sdk: flutter

  # Basicaly the main database package
  sembast: ^3.3.0
  # Package that helps to choose which sembast database factory app should use,
  # based on platform (at compile of course)
  tekartik_app_flutter_sembast:
    git:
      url: https://github.com/tekartik/app_flutter_utils.dart
      ref: dart2_3
      path: app_sembast

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
