name: nz_tasks_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  nz_common: ^1.0.0
  nz_tags_models:
    path: ../nz_tags_models
  uuid: ^4.4.2

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^3.2.3
  json_serializable: ^6.8.0
  lints: ^6.0.0
