name: nz_tasks_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  freezed_annotation: ^2.4.4
  nz_common: ^1.0.0
  nz_tags_models:
    path: ../nz_tags_models
  uuid: ^4.4.2
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  lints: ^4.0.0
  test: ^1.24.0
