name: not_zero
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  envied: ^0.5.4+1
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.3.0
  flutter_riverpod: ^2.5.1
  form_builder_validators: ^11.0.0
  freezed_annotation: ^2.4.4
  go_router: ^14.2.1
  infinite_scroll_pagination: ^4.0.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logging: ^1.2.0
  supabase_flutter: ^2.5.8

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  envied_generator: ^0.5.4+1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_lint: ^2.3.10
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
