name: nz_flutter_core
description: "A new Flutter package project."
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  theme_tailor_annotation: ^3.0.1
  slang: ^3.31.1
  slang_flutter: ^3.31.0
  go_router: ^14.2.3
  intl: ^0.19.0
  nz_common:
    path: ../nz_common

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^4.0.0
  theme_tailor: ^3.0.1

