name: nz_flutter_core
description: "A new Flutter package project."
version: 1.0.0
publish_to: none
resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  theme_tailor_annotation: ^3.0.1
  slang: ^4.8.1
  slang_flutter: ^4.8.0
  go_router: ^16.2.4
  intl: ^0.20.0
  nz_common:
    path: ../nz_common
  flutter_riverpod: ^3.0.0
  dynamic_color: ^1.8.1

dev_dependencies:
  build_runner: ^2.4.12
  flutter_lints: ^6.0.0
  theme_tailor: ^3.0.1

