include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - android/*
    - ios/*
    - lib/**/*.g.dart
    - lib/**/*.freezed.dart
    - lib/**/*.tailor.dart
  errors:
    unnecessary_await_in_return: warning
    # Added since JsonKey and JsonSerializable should be used in "invalid" place with freezed
    invalid_annotation_target: ignore
    avoid_positional_boolean_parameters: ignore

linter:
  rules:
    public_member_api_docs: false
    one_member_abstracts: false
    # unused_element: false
    sort_pub_dependencies: false
    unnecessary_await_in_return: true
    prefer_final_locals: true
    cascade_invocations: false
    specify_nonobvious_property_types: false
