name: nz_common
description: Common lib for not_zero
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.0

# Add regular dependencies here.
dependencies:
  nz_io:
    path: ../nz_io

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.8
