name: nz_score_models
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.5.3

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  uuid: ^4.5.0

dev_dependencies:
  build_runner: ^2.4.12
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  lints: ^4.0.0
